const carData = [
  {
    id: 1,
    title: 'Toyota Corolla XLi',
    location: 'Lahore',
    image: 'https://cars.urdua.net/toyota/images/toyota-corolla-xli-2018-exterior.jpg',
    kilometers: '45,000 km',
    transmission: 'Manual',
    fuel: 'Petrol',
    seats: '5 seats',
    price: 'PKR 8,500',
    purpose: 'Long Tour, City Travel',
    type: 'Sedans', // Added
  },
  {
    id: 2,
    title: 'Honda City Aspire',
    location: 'Karachi',
    image: 'https://hondaquaideen.com/wp-content/uploads/2022/07/Honda-City-Aspire-1.5LAS-Image-Nine-876x535.jpg',
    kilometers: '30,000 km',
    transmission: 'Automatic',
    fuel: 'Petrol',
    seats: '5 seats',
    price: 'PKR 9,000',
    purpose: 'City Travel, Corporate Events',
    type: 'Sedans', // Added
  },
  {
    id: 3,
    title: 'Mercedes-Benz C-Class',
    location: 'Islamabad',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsRJVWqCAicIYhq7FYOTuCrxrgVCAOvZWf5w&s',
    kilometers: '20,000 km',
    transmission: 'Automatic',
    fuel: 'Petrol',
    seats: '5 seats',
    price: 'PKR 35,000',
    purpose: 'Wedding Occasions, VIP Events',
    type: 'Sedans', // Added
  },
  {
    id: 4,
    title: 'Suzuki Cultus VXR',
    location: 'Peshawar',
    image: 'https://cache1.pakwheels.com/ad_pictures/1089/suzuki-cultus-vxr-2022-108919038.jpg',
    kilometers: '50,000 km',
    transmission: 'Manual',
    fuel: 'Gasoline/Petrol',
    seats: '5 seats',
    price: 'PKR 6,500',
    purpose: 'City Travel, Short Trips',
    type: 'Hatchbacks', // Added
  },
  {
    id: 5,
    title: 'Toyota Fortuner',
    location: 'Faisalabad',
    image: 'https://cdn.motor1.com/images/mgl/02EE3/s1/toyota-fortuner-gr-sport-indonesia.webp',
    kilometers: '35,000 km',
    transmission: 'Automatic',
    fuel: 'Diesel',
    seats: '7 seats',
    price: 'PKR 25,000',
    purpose: 'Long Tour, Family Trips',
    type: 'SUVs', // Added
  },
  {
    id: 6,
    title: 'Suzuki Alto VXL',
    location: 'Quetta',
    image: 'https://suzukifortmotors.com/wp-content/uploads/2020/12/Alto-Solid-White-720x466.jpg',
    kilometers: '25,000 km',
    transmission: 'Automatic',
    fuel: 'Petrol',
    seats: '4 seats',
    price: 'PKR 5,500',
    purpose: 'City Travel, Short Trips',
    type: 'Hatchbacks', // Added
  },
  {
    id: 7,
    title: 'Honda BR-V',
    location: 'Multan',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0q4Wj4f_BRMkjV7TIqUthkXkZHC61oK_srQ&s',
    kilometers: '40,000 km',
    transmission: 'Automatic',
    fuel: 'Petrol',
    seats: '7 seats',
    price: 'PKR 12,000',
    purpose: 'Family Trips, Long Tour',
    type: 'SUVs', // Added
  },
  {
    id: 8,
    title: 'Audi A6',
    location: 'Rawalpindi',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSoiJg4ZpF3F8Di73_nD7ITHkdsH5NBjREQew&s',
    kilometers: '15,000 km',
    transmission: 'Automatic',
    fuel: 'Petrol',
    seats: '5 seats',
    price: 'PKR 40,000',
    purpose: 'Wedding Occasions, VIP Events',
    type: 'Sedans', // Added
  },
  {
    id: 9,
    title: 'Toyota Yaris GLi',
    location: 'Sialkot',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCIfAP_-lAlpxY4t0z9ajZmUGh5pWpNYKCmA&s',
    kilometers: '38,000 km',
    transmission: 'Manual',
    fuel: 'Petrol',
    seats: '5 seats',
    price: 'PKR 7,500',
    purpose: 'City Travel, Corporate Events',
    type: 'Sedans', // Added
  },
];

export default carData;